"""initial_schema

Revision ID: 2f5eae99f12f
Revises: 
Create Date: 2026-10-03 19:27:35.428774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5eae99f12f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.execute("CREATE SCHEMA IF NOT EXISTS telemetry")
    op.execute("CREATE SCHEMA IF NOT EXISTS knowledge")
    op.execute("CREATE SCHEMA IF NOT EXISTS analytics")
    op.execute("CREATE SCHEMA IF NOT EXISTS workflow")
    op.execute("CREATE SCHEMA IF NOT EXISTS iam")
    op.execute("CREATE SCHEMA IF NOT EXISTS system")
    op.create_table('analysis_runs',
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('engine_version', sa.String(length=100), nullable=True),
    sa.Column('runtime_mode', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('run_id'),
    schema='analytics'
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tag_number', sa.String(length=50), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('plant_unit', sa.String(length=255), nullable=True),
    sa.Column('plant_code', sa.String(length=50), nullable=True),
    sa.Column('equipment_type', sa.String(length=255), nullable=True),
    sa.Column('equipment_class', sa.String(length=50), nullable=True),
    sa.Column('discipline', sa.String(length=50), nullable=True),
    sa.Column('criticality', sa.String(length=30), nullable=True),
    sa.Column('design_life', sa.Text(), nullable=True),
    sa.Column('monitoring_method', sa.Text(), nullable=True),
    sa.Column('core_mode', sa.String(length=20), nullable=False),
    sa.Column('fla_amp', sa.Numeric(), nullable=True),
    sa.Column('linked_rca_ar_no', sa.String(length=100), nullable=True),
    sa.Column('failure_date', sa.Date(), nullable=True),
    sa.Column('dominant_failure_mode', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("core_mode IN ('hourly', 'weekly')", name='chk_assets_core_mode'),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('tag_number'),
    schema='core'
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('employee_id', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('discipline', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username'),
    schema='iam'
    )
    op.create_table('incidents',
    sa.Column('incident_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=True),
    sa.Column('mto_no', sa.String(length=100), nullable=True),
    sa.Column('ar_no', sa.String(length=100), nullable=True),
    sa.Column('plant', sa.String(length=100), nullable=True),
    sa.Column('tag_number', sa.String(length=100), nullable=True),
    sa.Column('equipment_class', sa.String(length=100), nullable=True),
    sa.Column('date_of_occurrence', sa.Date(), nullable=True),
    sa.Column('risk_case_title', sa.Text(), nullable=True),
    sa.Column('highest_impact', sa.String(length=255), nullable=True),
    sa.Column('pre_risk', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Numeric(), nullable=True),
    sa.Column('pic_rca', sa.String(length=100), nullable=True),
    sa.Column('overall_status', sa.String(length=255), nullable=True),
    sa.Column('discipline', sa.String(length=100), nullable=True),
    sa.Column('equipment_type', sa.String(length=100), nullable=True),
    sa.Column('component', sa.String(length=255), nullable=True),
    sa.Column('failure_mechanism', sa.String(length=255), nullable=True),
    sa.Column('downtime_hours', sa.Numeric(), nullable=True),
    sa.Column('actual_loss_kusd', sa.Numeric(), nullable=True),
    sa.Column('potential_loss_kusd', sa.Numeric(), nullable=True),
    sa.Column('total_loss_kusd', sa.Numeric(), nullable=True),
    sa.Column('rca_due_date', sa.Date(), nullable=True),
    sa.Column('month_year', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('incident_id'),
    schema='knowledge'
    )
    op.create_table('rca_headers',
    sa.Column('rca_header_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ar_no', sa.String(length=100), nullable=False),
    sa.Column('tag_number', sa.String(length=100), nullable=True),
    sa.Column('plant', sa.String(length=100), nullable=True),
    sa.Column('date_occurrence', sa.Date(), nullable=True),
    sa.Column('pre_risk', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Numeric(), nullable=True),
    sa.Column('pic_rca', sa.String(length=100), nullable=True),
    sa.Column('procedure_no', sa.String(length=100), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('root_cause_statement', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rca_header_id'),
    sa.UniqueConstraint('ar_no'),
    sa.UniqueConstraint('ar_no', name='uq_rca_headers_ar_no'),
    schema='knowledge'
    )
    op.create_table('seed_runs',
    sa.Column('seed_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('source_checksum', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assets_count', sa.Integer(), nullable=True),
    sa.Column('metadata_count', sa.Integer(), nullable=True),
    sa.Column('sensor_tags_count', sa.Integer(), nullable=True),
    sa.Column('equipment_limits_count', sa.Integer(), nullable=True),
    sa.Column('hourly_count', sa.Integer(), nullable=True),
    sa.Column('weekly_source_rows', sa.Integer(), nullable=True),
    sa.Column('weekly_measurements_count', sa.Integer(), nullable=True),
    sa.Column('incidents_count', sa.Integer(), nullable=True),
    sa.Column('rca_headers_count', sa.Integer(), nullable=True),
    sa.Column('rca_priority_count', sa.Integer(), nullable=True),
    sa.Column('rca_4p_count', sa.Integer(), nullable=True),
    sa.Column('rca_4m_count', sa.Integer(), nullable=True),
    sa.Column('rca_capa_count', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('seed_run_id'),
    schema='system'
    )
    op.create_table('condition_inferences',
    sa.Column('inference_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_state', sa.String(length=50), nullable=True),
    sa.Column('consequence_class', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('dominant_symptom', sa.Text(), nullable=True),
    sa.Column('health_index', sa.Numeric(), nullable=True),
    sa.Column('pca_anomaly_score', sa.Numeric(), nullable=True),
    sa.Column('max_zscore', sa.Numeric(), nullable=True),
    sa.Column('statistical_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['core.assets.asset_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analytics.analysis_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inference_id'),
    sa.UniqueConstraint('run_id', 'asset_id', name='uq_condition_inferences_run_asset'),
    schema='analytics'
    )
    op.create_table('parameter_forecasts',
    sa.Column('forecast_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('canonical_param', sa.String(length=255), nullable=False),
    sa.Column('anchor_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimate', sa.Numeric(), nullable=True),
    sa.Column('lower_bound', sa.Numeric(), nullable=True),
    sa.Column('upper_bound', sa.Numeric(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('model_family', sa.String(length=100), nullable=True),
    sa.Column('model_type', sa.String(length=100), nullable=True),
    sa.Column('model_quality', sa.String(length=100), nullable=True),
    sa.Column('mae', sa.Numeric(), nullable=True),
    sa.Column('rmse', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['core.assets.asset_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analytics.analysis_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('forecast_id'),
    sa.UniqueConstraint('run_id', 'asset_id', 'canonical_param', 'target_time', name='uq_param_forecast_run_asset_param_time'),
    schema='analytics'
    )
    op.create_table('rca_matches',
    sa.Column('rca_match_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('matched_ar_no', sa.String(length=100), nullable=True),
    sa.Column('similarity_score', sa.Numeric(), nullable=True),
    sa.Column('evidence_strength', sa.String(length=100), nullable=True),
    sa.Column('rank_no', sa.Integer(), nullable=True),
    sa.Column('current_supporting_evidence', sa.Text(), nullable=True),
    sa.Column('historical_verified_evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['core.assets.asset_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analytics.analysis_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rca_match_id'),
    sa.UniqueConstraint('run_id', 'asset_id', 'matched_ar_no', name='uq_rca_matches_run_asset_ar'),
    schema='analytics'
    )
    op.create_table('asset_metadata',
    sa.Column('metadata_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('parameter', sa.String(length=255), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('source_sheet', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['core.assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metadata_id'),
    sa.UniqueConstraint('asset_id', 'parameter', name='uq_asset_metadata_param'),
    schema='core'
    )
    op.create_table('equipment_limits',
    sa.Column('limit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('parameter', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('alarm_limit', sa.Numeric(), nullable=False),
    sa.Column('trip_limit', sa.Numeric(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_sheet', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('alarm_limit != trip_limit', name='chk_equipment_limits_alarm_trip_diff'),
    sa.ForeignKeyConstraint(['asset_id'], ['core.assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('limit_id'),
    sa.UniqueConstraint('asset_id', 'parameter', 'effective_from', name='uq_equipment_limits_asset_param_from'),
    schema='core'
    )
    op.create_table('sensor_tags',
    sa.Column('tag_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('pi_tag', sa.String(length=255), nullable=False),
    sa.Column('canonical_param', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('digital_set', sa.Text(), nullable=True),
    sa.Column('engineering_unit', sa.String(length=100), nullable=True),
    sa.Column('span', sa.Numeric(), nullable=True),
    sa.Column('typical_value', sa.Numeric(), nullable=True),
    sa.Column('zero_value', sa.Numeric(), nullable=True),
    sa.Column('instrument_tag', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['core.assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('asset_id', 'pi_tag', name='uq_sensor_tags_asset_pi_tag'),
    schema='core'
    )
    op.create_table('rca_4m_verifications',
    sa.Column('verification_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ar_no', sa.String(length=100), nullable=False),
    sa.Column('factor_id', sa.String(length=100), nullable=False),
    sa.Column('factor_category', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('evidence_finding', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ar_no'], ['knowledge.rca_headers.ar_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verification_id'),
    sa.UniqueConstraint('ar_no', 'factor_id', name='uq_rca_4m_ar_factor'),
    schema='knowledge'
    )
    op.create_table('rca_4p_verifications',
    sa.Column('verification_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ar_no', sa.String(length=100), nullable=False),
    sa.Column('parameter_id', sa.String(length=100), nullable=False),
    sa.Column('problem_phenomenon_parameter', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('evidence_finding', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ar_no'], ['knowledge.rca_headers.ar_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verification_id'),
    sa.UniqueConstraint('ar_no', 'parameter_id', name='uq_rca_4p_ar_param'),
    schema='knowledge'
    )
    op.create_table('rca_capa_actions',
    sa.Column('capa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ar_no', sa.String(length=100), nullable=False),
    sa.Column('rc', sa.String(length=100), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('action_plan', sa.Text(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('pic', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ar_no'], ['knowledge.rca_headers.ar_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capa_id'),
    sa.UniqueConstraint('fingerprint', name='uq_rca_capa_fingerprint'),
    schema='knowledge'
    )
    op.create_table('rca_priority_matrix',
    sa.Column('priority_matrix_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ar_no', sa.String(length=100), nullable=False),
    sa.Column('root_cause_id', sa.String(length=100), nullable=False),
    sa.Column('impact_level', sa.String(length=100), nullable=True),
    sa.Column('control_level', sa.String(length=100), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('description_short', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ar_no'], ['knowledge.rca_headers.ar_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('priority_matrix_id'),
    sa.UniqueConstraint('ar_no', 'root_cause_id', name='uq_rca_priority_ar_root_cause'),
    schema='knowledge'
    )
    op.create_table('hourly_measurements',
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feed', sa.Numeric(), nullable=True),
    sa.Column('disp', sa.Numeric(), nullable=True),
    sa.Column('vib', sa.Numeric(), nullable=True),
    sa.Column('temp', sa.Numeric(), nullable=True),
    sa.Column('amp', sa.Numeric(), nullable=True),
    sa.Column('plant_rate', sa.Numeric(), nullable=True),
    sa.Column('run_status', sa.String(length=20), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("run_status IS NULL OR run_status IN ('ON', 'OFF', 'UNKNOWN')", name='chk_hourly_run_status'),
    sa.ForeignKeyConstraint(['asset_id'], ['core.assets.asset_id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'measured_at'),
    schema='telemetry'
    )
    op.create_index('idx_hourly_asset_time', 'hourly_measurements', ['asset_id', 'measured_at'], unique=False, schema='telemetry')
    op.create_table('weekly_measurements',
    sa.Column('weekly_measurement_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('parameter', sa.String(length=255), nullable=False),
    sa.Column('measured_value', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('health_status', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('derivation_method', sa.String(length=100), nullable=True),
    sa.Column('derivation_version', sa.String(length=50), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_column', sa.String(length=255), nullable=True),
    sa.Column('source_sheet', sa.String(length=255), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['core.assets.asset_id'], ),
    sa.PrimaryKeyConstraint('weekly_measurement_id'),
    sa.UniqueConstraint('asset_id', 'record_date', 'parameter', 'source_type', name='uq_weekly_asset_date_param_source'),
    schema='telemetry'
    )
    op.create_index('idx_weekly_asset_date', 'weekly_measurements', ['asset_id', 'record_date'], unique=False, schema='telemetry')
    op.create_table('problem_tickets',
    sa.Column('ticket_id', sa.String(length=100), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('condition_state', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('owner_role', sa.String(length=255), nullable=True),
    sa.Column('ticket_state', sa.String(length=100), nullable=True),
    sa.Column('action_status', sa.String(length=100), nullable=True),
    sa.Column('normal_streak', sa.Integer(), nullable=False),
    sa.Column('matched_rca_ar', sa.String(length=100), nullable=True),
    sa.Column('evidence_strength', sa.String(length=100), nullable=True),
    sa.Column('operator_decision', sa.String(length=100), nullable=True),
    sa.Column('last_operator_name', sa.String(length=255), nullable=True),
    sa.Column('operator_comment', sa.Text(), nullable=True),
    sa.Column('field_observation', sa.Text(), nullable=True),
    sa.Column('update_source', sa.String(length=50), nullable=True),
    sa.Column('last_observation_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['core.assets.asset_id'], ),
    sa.PrimaryKeyConstraint('ticket_id'),
    schema='workflow'
    )
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ticket_id', sa.String(length=100), nullable=True),
    sa.Column('asset_id', sa.BigInteger(), nullable=True),
    sa.Column('update_source', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('previous_ticket_state', sa.String(length=100), nullable=True),
    sa.Column('new_ticket_state', sa.String(length=100), nullable=True),
    sa.Column('previous_action_status', sa.String(length=100), nullable=True),
    sa.Column('new_action_status', sa.String(length=100), nullable=True),
    sa.Column('operator_decision', sa.String(length=100), nullable=True),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('owner_role', sa.String(length=255), nullable=True),
    sa.Column('field_observation', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['core.assets.asset_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['workflow.problem_tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('audit_id'),
    schema='workflow'
    )
    op.create_index('idx_audit_logs_ticket_time', 'audit_logs', ['ticket_id', 'event_time'], unique=False, schema='workflow')
    op.create_table('operator_inputs',
    sa.Column('operator_input_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.String(length=100), nullable=True),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('visible_leakage', sa.String(length=50), nullable=True),
    sa.Column('abnormal_noise', sa.String(length=50), nullable=True),
    sa.Column('abnormal_vibration', sa.String(length=50), nullable=True),
    sa.Column('local_temperature_confirmed', sa.String(length=50), nullable=True),
    sa.Column('field_observation', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('owner_role', sa.String(length=255), nullable=True),
    sa.Column('action_status', sa.String(length=100), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['core.assets.asset_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['workflow.problem_tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('operator_input_id'),
    schema='workflow'
    )
    op.create_index('idx_operator_inputs_ticket_time', 'operator_inputs', ['ticket_id', 'submitted_at'], unique=False, schema='workflow')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_operator_inputs_ticket_time', table_name='operator_inputs', schema='workflow')
    op.drop_table('operator_inputs', schema='workflow')
    op.drop_index('idx_audit_logs_ticket_time', table_name='audit_logs', schema='workflow')
    op.drop_table('audit_logs', schema='workflow')
    op.drop_table('problem_tickets', schema='workflow')
    op.drop_index('idx_weekly_asset_date', table_name='weekly_measurements', schema='telemetry')
    op.drop_table('weekly_measurements', schema='telemetry')
    op.drop_index('idx_hourly_asset_time', table_name='hourly_measurements', schema='telemetry')
    op.drop_table('hourly_measurements', schema='telemetry')
    op.drop_table('rca_priority_matrix', schema='knowledge')
    op.drop_table('rca_capa_actions', schema='knowledge')
    op.drop_table('rca_4p_verifications', schema='knowledge')
    op.drop_table('rca_4m_verifications', schema='knowledge')
    op.drop_table('sensor_tags', schema='core')
    op.drop_table('equipment_limits', schema='core')
    op.drop_table('asset_metadata', schema='core')
    op.drop_table('rca_matches', schema='analytics')
    op.drop_table('parameter_forecasts', schema='analytics')
    op.drop_table('condition_inferences', schema='analytics')
    op.drop_table('seed_runs', schema='system')
    op.drop_table('rca_headers', schema='knowledge')
    op.drop_table('incidents', schema='knowledge')
    op.drop_table('users', schema='iam')
    op.drop_table('assets', schema='core')
    op.drop_table('analysis_runs', schema='analytics')
    # ### end Alembic commands ###
